# Generated by Django 6.0 on 2025-12-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_creatsed_at_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='adres',
            field=models.TextField(default='г.Москва'),
        ),
    ]
