# Generated by Django 6.0 on 2025-12-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creatsed_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='initiative',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
