# Generated by Django 6.0 on 2025-12-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initiative_adres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Инфо'),
        ),
    ]
